### ISSUE TITLE
Darkorbit X-2 Map bot flees to middle gate jumping to 4-4 and then dies

### ISSUE THREAD

**Issue by BottingMarket** [berkeleyinc/Golem#73]
**Describe the bug**
X-2 Map bot flees to middle gate jumping to 4-4 and then dies
**only on spaceball event!**

**To Reproduce**
Have the bot flee on X-2 map when spaceball is on.

**Expected behavior**
Bot should only flee to the 3 outside gates not the middle one.

**Screenshots**
![Desktop Screenshot 2019 04 09 - 21 57 00 34](https://user-images.githubusercontent.com/45576830/55831141-ba9e8280-5b12-11e9-9404-5538b05ce7e5.png)

**Additional context**
-

**Comment by crashblaster** [comment]
*irony on* That is not a bug its a feature ^^ The bot is collecting some nice spaceball bonus boxes :D *irony off*

**Comment by crashblaster** [comment]
should be fixed with these two updates:
 v4.0.18.8-1: DO: Won't fly into gates in the center
 v4.0.18.8-1: DO: Won't flee to 4-4

**Comment by crashblaster** [comment]
reopen because guys have responded that this bug still exists on discord

**Comment by BottingMarket** [comment]
Yes I can confirm it still happened when spaceball event is on it jumps the middle gate in the X-2 Maps

**Comment by crashblaster** [comment]
should be fixed now:
Update v4.25
- DO: fix: Won't jump through spaceball gate
